# Generated by Django 2.2.5 on 2019-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=50)),
                ('info', models.TextField(max_length=2000)),
            ],
        ),
    ]
